### ISSUE TITLE
[Suggestion] Add compatibility for DiscordSRV

### ISSUE THREAD

**Issue by FaultyFunctions** [jwkerr/HopperFilter#3]
When you `Shift + Left Click` a hopper and then type in chat to rename it, that message doesn't show up in-game but it does show up on Discord when using DiscordSRV.

![image](https://github.com/jwkerr/HopperFilter/assets/6508045/a426df8b-1626-4b6d-b729-33ea336bf151)

**Comment by jwkerr** [comment]
can't reproduce, looks like its a discordsrv config setting
![image](https://github.com/jwkerr/HopperFilter/assets/49851457/c3e88e33-81b1-49d6-aed4-0dad62896939)

**Comment by FaultyFunctions** [comment]
Hmm okay I'll take a look. Thanks for checking!

**Comment by jwkerr** [comment]
@FaultyFunctions did you just find this plugin on modrinth by the way? looks like its getting a lot more attention than most the stuff i make

**Comment by FaultyFunctions** [comment]
Yes I did! It solved a problem I had with hoppers where if they are stacked on top of each other they will pull down instead of into the chests they are pointed into. So really great plugin, thank you for it! I'm pairing it with [Smart Item Sort](https://www.spigotmc.org/resources/smart-item-sort.100831/) on my server.
