### ISSUE TITLE
Not able to filter water bottle, awkwand, mundane and thick potion.

### ISSUE THREAD

**Issue by asyi0** [jwkerr/HopperFilter#4]
It does not seem to be able to filter no effect potions.

I tried
`potion&~awkward`, `potion&~water`, `potion&~null` , `potion&~`
but does not works.

This is just a minor issue that I found when I tried to make a hopper that could only pass the awkward potion in an auto potion machine.

**Comment by jwkerr** [comment]
@asyi0 use the syntax `=awkward_potion`

**Comment by jwkerr** [comment]
it filters by display name, so that includes items renamed that
