### ISSUE TITLE
[Bug] Using HopperFilters, if an item has the name as the filter (Example, *cactus for cactus), and it attempts to go through, BUT the hopper is filled, it will not move and instead clump up the system, leading to an overflow affect.

### ISSUE THREAD

**Issue by styui** [jwkerr/HopperFilter#5]
[Bug] Using HopperFilters, if an item has the name as the filter (Example, *cactus for cactus), and it attempts to go through, BUT the hopper is filled, it will not move and instead clump up the system, leading to an overflow affect.

This is an example of where there is an open flow of items on the top hopper, and a filter hopper below it.

It attempts to go into that hopper, but as it is full, it is impossible for the item to attempt to move on.

**Comment by keijodputt** [comment]
Experienced this a couple days ago. Hopper renamed "cactus" pointing to a furnace, when full of cactus, will affect the hopper above it, stopping the cactus from "flowing" through the hoppers chain.

**Comment by jwkerr** [comment]
https://modrinth.com/plugin/hopperfilter/version/0.3.5
