### ISSUE TITLE
[Suggestion] Add check for Instrument tags that allows goat horns can be filtered by type

### ISSUE THREAD

**Issue by asyi0** [jwkerr/HopperFilter#6]
I tried to use [Instrument tags](https://minecraft.wiki/w/Tag#Instrument_tags) to filter goat horns, but it did not work.
I checked [the source](
https://github.com/jwkerr/HopperFilter/blob/8f2cda80e79949303b5d4f28199ab6c22228123a/src/main/java/net/earthmc/hopperfilter/listener/InventoryActionListener.java#L149) and it seems that only Blocks tags and Items tags are supported.
If possible, please add a check for Instrument tags to enable goat horn filtering.

**Comment by jwkerr** [comment]
how important is this to be added for you?

**Comment by asyi0** [comment]
It would be useful to create a goat horn shop, but not really that important.
