### ISSUE TITLE
"Bow" and "*Bow" Won't Filter From Chest if Not in First Chest Slot

### ISSUE THREAD

**Issue by austephner** [jwkerr/HopperFilter#9]
Not sure if I'm doing something wrong but I have a hopper that was named "*bow" which wouldn't take bows out of the chest above it unless the bow appeared in the very first slot of the chest. I changed the name of the hopper to "Bow" and it has the same behaviour. Great plugin so far though!

https://github.com/user-attachments/assets/9755de50-0b28-46e6-82f3-fc5d58b27660

**Comment by jwkerr** [comment]
The plugin acts on hopper events, and vanilla takes from the first slot so the server is attempting to send another item through but HopperFilter cancels it as it does not pass the filter below, so nothing moves. The plugin does not check other slots on its own.

Typically if there will be many types of items flowing through you will need to make a hopper chain that flows over a series of chests and into a "junk" chest for any stuff that couldn't be sorted.

I can take a picture later, but many hoppers facing sideways into each other on top, then hoppers facing down into chests below the sideways hoppers.

**Comment by austephner** [comment]
> The plugin acts on hopper events, and vanilla takes from the first slot so the server is attempting to send another item through but HopperFilter cancels it as it does not pass the filter below, so nothing moves. The plugin does not check other slots on its own.
> 
> Typically if there will be many types of items flowing through you will need to make a hopper chain that flows over a series of chests and into a "junk" chest for any stuff that couldn't be sorted.
> 
> I can take a picture later, but many hoppers facing sideways into each other on top, then hoppers facing down into chests below the sideways hoppers.

Okay understood. I am just an MC noob. I know what I have to do now, thank you for the explanation.
